
-- 1. CLEANUP (Drop existing to ensure fresh start)
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS template_history CASCADE;
DROP TABLE IF EXISTS sms_tracker CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS discounts CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS product_categories CASCADE;
DROP TABLE IF EXISTS service_categories CASCADE;
DROP TABLE IF EXISTS store_settings CASCADE;

-- 2. CREATE TABLES (Strictly adhering to provided definitions)

-- Appointments
create table public.appointments (
  id text not null,
  "petName" text null,
  "ownerName" text null,
  "serviceId" text null,
  date text null,
  time text null,
  status text null,
  "groomerId" text null,
  "contactNumber" text null,
  "petBreed" text null,
  "petColor" text null,
  "weightSize" text null,
  "hairCut" text null,
  email text null,
  constraint appointments_pkey primary key (id)
) TABLESPACE pg_default;

-- Clients
create table public.clients (
  id text not null,
  name text null,
  contact_number text null,
  address text null,
  notes text null,
  first_seen text null,
  pets jsonb null default '[]'::jsonb,
  email text null,
  constraint clients_pkey primary key (id)
) TABLESPACE pg_default;

-- Devices
create table public.devices (
  id text not null,
  name text null,
  status text null default 'PENDING'::text,
  "lastActive" text null,
  ip text null,
  location text null,
  os text null,
  browser text null,
  device_type text null,
  custom_name text null,
  constraint devices_pkey primary key (id)
) TABLESPACE pg_default;

-- Discounts
create table public.discounts (
  id text not null,
  name text null,
  type text null,
  value numeric null,
  active boolean null,
  trigger_type text null default 'MANUAL'::text,
  trigger_value text null,
  start_date text null,
  end_date text null,
  is_permanent boolean null default true,
  constraint discounts_pkey primary key (id)
) TABLESPACE pg_default;

-- Logs
create table public.logs (
  id text not null,
  action text null,
  details text null,
  timestamp text null,
  "userId" text null,
  "referenceId" text null,
  constraint logs_pkey primary key (id)
) TABLESPACE pg_default;

-- Messages
create table public.messages (
  id text not null,
  client_id text not null,
  direction text not null,
  channel text not null,
  content text not null,
  timestamp timestamp with time zone null default now(),
  status text null default 'SENT'::text,
  read boolean null default false,
  constraint messages_pkey primary key (id),
  constraint messages_client_id_fkey foreign KEY (client_id) references clients (id) on delete CASCADE,
  constraint messages_channel_check check (
    (channel = any (array['SMS'::text, 'EMAIL'::text]))
  ),
  constraint messages_direction_check check (
    (
      direction = any (array['INBOUND'::text, 'OUTBOUND'::text])
    )
  )
) TABLESPACE pg_default;

-- Product Categories
create table public.product_categories (
  id bigint generated by default as identity not null,
  name text null,
  constraint product_categories_pkey primary key (id),
  constraint product_categories_name_key unique (name)
) TABLESPACE pg_default;

-- Products
create table public.products (
  id text not null,
  name text null,
  price numeric null,
  category text null,
  stock numeric null,
  "isService" boolean null,
  cost numeric null default 0,
  constraint products_pkey primary key (id)
) TABLESPACE pg_default;

-- Service Categories
create table public.service_categories (
  id bigint generated by default as identity not null,
  name text null,
  constraint service_categories_pkey primary key (id),
  constraint service_categories_name_key unique (name)
) TABLESPACE pg_default;

-- SMS Tracker
create table public.sms_tracker (
  hour_key text not null,
  count integer null default 0,
  updated_at timestamp with time zone null default timezone ('utc'::text, now()),
  constraint sms_tracker_pkey primary key (hour_key)
) TABLESPACE pg_default;

-- Store Settings
create table public.store_settings (
  id text not null,
  name text null,
  address text null,
  "contactNumber" text null,
  "vatRate" numeric null,
  "gcashNumber" text null,
  "gcashQr" text null,
  "receiptHeader" text null,
  "receiptFooter" text null,
  logo text null,
  sms_enabled boolean null default false,
  text_bee_api_key text null,
  text_bee_device_id text null,
  email_enabled boolean null default false,
  email_api_key text null,
  email_sender_name text null,
  email_service_id text null,
  email_template_id text null,
  email_public_key text null,
  google_client_id text null,
  google_client_secret text null,
  google_refresh_token text null,
  sms_template_upcoming text null,
  email_subject_upcoming text null,
  email_body_upcoming text null,
  sms_template_waiting text null,
  email_subject_waiting text null,
  email_body_waiting text null,
  sms_template_ongoing text null,
  email_subject_ongoing text null,
  email_body_ongoing text null,
  sms_template_completed text null,
  email_subject_completed text null,
  email_body_completed text null,
  sms_template_promo text null,
  email_subject_promo text null,
  email_body_promo text null,
  email_footer_text text null default 'Thank you for trusting us with your Paw friend!'::text,
  constraint store_settings_pkey primary key (id)
) TABLESPACE pg_default;

-- Template History
create table public.template_history (
  id uuid not null default gen_random_uuid (),
  category text not null,
  channel text not null,
  content text not null,
  created_at timestamp with time zone null default now(),
  constraint template_history_pkey primary key (id)
) TABLESPACE pg_default;

-- Transactions
create table public.transactions (
  id text not null,
  items jsonb null,
  subtotal numeric null,
  vat numeric null,
  total numeric null,
  discount numeric null,
  "paymentMethod" text null,
  "gcashRef" text null,
  date text null,
  "cashierId" text null,
  "cashReceived" numeric null,
  constraint transactions_pkey primary key (id)
) TABLESPACE pg_default;

-- Users
create table public.users (
  id text not null,
  name text null,
  pin text null,
  role text null,
  constraint users_pkey primary key (id)
) TABLESPACE pg_default;

-- 3. ENABLE RLS & POLICIES
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE discounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms_tracker ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access" ON store_settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON appointments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON transactions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON discounts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON devices FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON sms_tracker FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON product_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON service_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON template_history FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access" ON messages FOR ALL USING (true) WITH CHECK (true);

-- 4. UTILITY FUNCTION
CREATE OR REPLACE FUNCTION get_database_size_bytes()
RETURNS bigint
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT pg_database_size(current_database());
$$;

-- 5. REPLICA IDENTITY
ALTER TABLE store_settings REPLICA IDENTITY FULL;
ALTER TABLE products REPLICA IDENTITY FULL;
ALTER TABLE appointments REPLICA IDENTITY FULL;
ALTER TABLE transactions REPLICA IDENTITY FULL;
ALTER TABLE clients REPLICA IDENTITY FULL;
ALTER TABLE users REPLICA IDENTITY FULL;
ALTER TABLE devices REPLICA IDENTITY FULL;
ALTER TABLE messages REPLICA IDENTITY FULL;
